### ISSUE TITLE
ddcb_capi.c: Using sem_wait() without proper EINT return code handling

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-genwqe/genwqe-user#111]
Eberhart and I reviewed the code and found that we seem not properly handling EINT return codes in that file, especially when sitting in sem_wait(). We are not sure how often this really might happen, but fixing this is probably a good idea.

**Comment by ibm-genwqe** [comment]
i pushed out a branch (issue_111) and i am testing now on RHEL
There is no Pull request yet. Still testing

**Comment by fhaverkamp** [comment]
I suggest to include this in the master branch too.
