### ISSUE TITLE
network ports

### ISSUE THREAD

**Issue by ianamunoz** [ibm-genwqe/genwqe-user#127]
Is there any information about the network ports on the EJ1B? I have installed the device and tested the software, all seems to be functional. Are the network ports on the EJ1B functional? If so where can I find documentation for configuration.

**Comment by fhaverkamp** [comment]
Hi Ian,

the network ports on the EJ1B are not used for the gzip/DEFLATE application. The card hardware is derived from a generic design such that it could be reused for other applications too.  I assume that for other applications the ports should work (if all required parts are populated). But I really cannot tell for sure if this valid for this version of the card.

You wrote that the software seems functional. That is great to hear. Please let us know your experiences when trying it out.

Regards

Frank
