### ISSUE TITLE
FTBFS on any 32-bit arches

### ISSUE THREAD

**Issue by xnox** [ibm-genwqe/genwqe-user#141]
Hello,

genwqe-user fails to build from source on any 32-bit arches in Debian.

Please see build logs with failures at:

https://buildd.debian.org/status/package.php?p=genwqe-user

Regards,

Dimitri.

**Comment by xnox** [comment]
suggestion got posted on the debian bug tracker as to how to potentially fix this

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855377#10

Any progress on this? This issue blocks including updated genwqe in Ubuntu.

**Comment by leitao** [comment]
I think I have a fix for it:
https://github.com/ibm-genwqe/genwqe-user/pull/142

**Comment by fhaverkamp** [comment]
Hi Dimitry, please have a look if Brenos #142 does the trick. Thanks.

**Comment by fhaverkamp** [comment]
I think this is ok now.
