### ISSUE TITLE
Static analysis results by Coverity Scan

### ISSUE THREAD

**Issue by r4f4** [ibm-genwqe/genwqe-user#145]
I ran coverity scan over genwqe-user codebase and the results can be found [here](http://people.redhat.com/~rdossant/scan-results.err).

I'll try to send patches to some of the issues as time allows it.

**Comment by fhaverkamp** [comment]
@r4f4 I think this got merged, right? Can we close this?

**Comment by r4f4** [comment]
@fhaverkamp Yes, it is merged in commit bccbcf24f6c654f384b1bea0868192398173d4b2.
I'm closing this issue. Thank you!
