### ISSUE TITLE
Software fallback to SAP libz fails with compression error

### ISSUE THREAD

**Issue by ghost** [ibm-genwqe/genwqe-user#159]
Scenario:
SAP Hana 2.0, libzADC dynamically linked to Hana, dynamical fallback to the SAP libz library.

Bug:
Compression errors

Detailed description will follow. I will try to produce a "minimal not working example".

**Comment by fhaverkamp** [comment]
Hi Maurice, do you have any more debug hints, traces or even example code yet?

**Comment by ghost** [comment]
No, unfortunately I don't have the time to address this issue up right now

**Comment by fhaverkamp** [comment]
@mdebatin Is this still needed? Or should we rather close the issue and reopen/create new if it reoccurs and if we have a procedure to reproduce this?

**Comment by ghost** [comment]
Hi, I think for now we can close the issue and reopen it if it occurs in another scenario.
