### ISSUE TITLE
file information (stat) is not preserved

### ISSUE THREAD

**Issue by sebott** [ibm-genwqe/genwqe-user#16]
# ll foo

-rwxr-xr-x 1 root root 95349752 Sep 25 13:24 foo
# src/genwqe-user/tools/genwqe_gzip foo
# src/genwqe-user/tools/genwqe_gunzip foo.gz
# ll foo

-rw-r--r-- 1 root root 95349752 Sep 25 13:24 foo

**Comment by fhaverkamp** [comment]
Yes, that looks like a bug. Thanks for reporting it. I spend you a coffee next week, if you send a patch for merging ;-).

**Comment by ibm-genwqe** [comment]
please set or check if

"git config core.filemode=true"

is true


Mit freundlichen Grüßen / Kind regards

Eberhard S. Amann

zEDC Firmware
IBM Systems &Technology Group, Integrated Systems Development
Opens Systems Hardware Development
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
 Phone:            +49-7034-274-3029          IBM Deutschland                      (Embedded 
                                                                                 image moved 
                                                                                    to file: 
                                                                               pic59535.gif) 
                                                                                             
 E-Mail:           esa@de.ibm.com             Schoenaicher Str. 220                          
                                                                                             
                                              71032 Boeblingen                               
                                                                                             
                                              Germany                                        
                                                                                             
                                                                                             
                                                                                             
                                                                                             
                                                                                             
 IBM Deutschland                                                                             
 Research &                                                                                  
 Development                                                                                 
 GmbH /                                                                                      
 Vorsitzender des                                                                            
 Aufsichtsrats:                                                                              
 Martina Koederitz                                                                           
                                                                                             
 Geschäftsführung:                                                                           
 Dirk Wittkopp                                                                               
 Sitz der                                                                                    
 Gesellschaft:                                                                               
 Böblingen /                                                                                 
 Registergericht:                                                                            
 Amtsgericht                                                                                 
 Stuttgart, HRB                                                                              
 243294                                                                                      
                                                                                             





From:	Frank Haverkamp <notifications@github.com>
To:	ibm-genwqe/genwqe-user <genwqe-user@noreply.github.com>
Date:	25.09.2015 13:32
Subject:	Re: [genwqe-user] file information (stat) is not preserved
            (#16)



Yes, that looks like a bug.


—
Reply to this email directly or view it on GitHub.

**Comment by sebott** [comment]
On Sun, 27 Sep 2015, Eberhard S. Amann wrote:

> please set or check if
> 
> "git config core.filemode=true"
> 
> is true

The genwqe-user files are fine. It's that genwqe_gzip modifies the
file attributes:

# ll foo

-rwxr-xr-x 1 root root 95349752 Sep 25 13:24 foo

# src/genwqe-user/tools/genwqe_gzip foo

# src/genwqe-user/tools/genwqe_gunzip foo.gz

# ll foo

-rw-r--r-- 1 root root 95349752 Sep 25 13:24 foo

regards,
Sebastian

**Comment by fhaverkamp** [comment]
Hi Sebastian,

commit 919344155ed44e88e9e160d81c427996d513bbdc contains a fix proposal. Please let me know if that works out for you. I have already requested merge ;-). So we need to stop Eberhard, if that was too quick.

Thanks

Frank

**Comment by sebott** [comment]
Looks good!
Thanks for the quick fix,
Sebastian
