### ISSUE TITLE
00008d94.00008d96: WARNING: 5 sec timeout while waiting for interrupt! rc: 0 --> -418

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-genwqe/genwqe-user#35]
I sometimes get those messages. Eberhard seems to have a fix for this.

**Comment by ibm-genwqe** [comment]
i did fix this with my latest patches for directed mode.
This was a left over message which can happen but its not allways a fault

**Comment by fhaverkamp** [comment]
Should be fixed now. Thanks.
