### ISSUE TITLE
Do not ship binaries with interpreter extensions

### ISSUE THREAD

**Issue by xnox** [ibm-genwqe/genwqe-user#75]
As per Debian Policy, binaries shipped in standard $PATH should not end with extensions. E.g. it should /usr/bin/tool, rather than /usr/bin/tool.sh

Furthermore shipping:
bin/zlib_mt_perf
bin/zlib_mt_perf.sh

is confusing. Please rename ".sh" scripts to be installed without an extension, and have a unique name. And possibly choose a better location to ship them at, e.g. unding /usr/lib, or possibly even /usr/share/doc/genwqe/.

Fixes required for:
bin/zlib_mt_perf.sh
bin/zlib_test_gz.sh

**Comment by fhaverkamp** [comment]
I added the following change to address the issue mentioned above:
https://github.com/ibm-genwqe/genwqe-user/commit/f757fe777077783c2e6256e5bc137d61441b7f67

I renamed zlib_mt_perf.sh to genwqe_mt_perf and zlib_test_gz.sh to genwqe_test_gz. I updated the spec file too and the Makefile.
