### ISSUE TITLE
Makefile: Calling make a 2nd time does a full build again

### ISSUE THREAD

**Issue by ibm-genwqe** [ibm-genwqe/genwqe-user#89]
Makefile seems to be modified.
Try using make, and run again,
The code will be build once more.
Please fix.

**Comment by fhaverkamp** [comment]
4.0.7 was the last not showing this effect. We introduced some fixes to enable parallel build via make -jCPUs. That might have caused this. Did not run git bisect yet to figure out what broke it.

**Comment by fhaverkamp** [comment]
[haverkam@oc7383187364 genwqe-user]$ make clean
[haverkam@oc7383187364 genwqe-user]$ make -j16
    [CC]    libzHW.o
    [CC]    inflate.o
    [CC]    deflate.o
    [CC]    libcard.o
    [CC]    libddcb.o
    [CC]    ddcb_card.o
    [CC]    wrapper.o
    [CC]    hardware.o
    [CC]    software.o
    [CC]    ddcb_card.o
    [CC]    inflate.o
    [CC]    libcard.o
    [CC]    deflate.o
    [CC]    libzHW.o
    [CC]    wrapper.o
    [CC]    software.o
    [CC]    hardware.o
    [CC]    libddcb.o
    [LD]    __libzHW.o
    [LD]    __libcard.o
    [LD]    __libDDCB.o
    [CC]    libDDCB.so.4.0.16-11-g0350
    [AR]    libDDCB.a
    [AR]    libzHW.a
    [LD]    __libzADC.o
    [CC]    libcard.so.4.0.16-11-g0350
    [CC]    libzHW.so.4.0.16-11-g0350
    [AR]    libcard.a
    [AR]    libzADC.a
    [CC]    libzADC.so.4.0.16-11-g0350
    [CC]    genwqe_update.o
    [CC]    genwqe_gzip.o
    [CC]    genwqe_gunzip.o
    [CC]    zlib_mt_perf.o
    [CC]    force_cpu.o
    [CC]    genwqe_memcopy.o
    [CC]    genwqe_echo.o
    [CC]    genwqe_peek.o
    [CC]    genwqe_poke.o
    [CC]    genwqe_cksum.o
    [CC]    genwqe_vpd_common.o
    [CC]    genwqe_vpdconv.o
    [CC]    genwqe_vpdupdate.o
    [CC]    genwqe_csv2vpd.o
    [CC]    genwqe_ffdc.o
    [CC]    genwqe_update
    [CC]    genwqe_gunzip
    [CC]    genwqe_gzip
    [CC]    genwqe_cksum
    [CC]    genwqe_csv2vpd
    [CC]    genwqe_echo
    [CC]    zlib_mt_perf
    [CC]    genwqe_vpdconv
    [CC]    genwqe_peek
    [CC]    genwqe_poke
    [CC]    genwqe_vpdupdate
    [CC]    genwqe_ffdc
    [CC]    genwqe_memcopy
[haverkam@oc7383187364 genwqe-user]$ make -j16
[haverkam@oc7383187364 genwqe-user]$ make -j16

So it is not fully true that the build is entirely repeated. But I think it might have something to do with the libcxl integration we did. I need to check that one.

**Comment by fhaverkamp** [comment]
haver@tul2eth3:~/genwqe/genwqe-user$ make clean
haver@tul2eth3:~/genwqe/genwqe-user$ make -j160
    [CC]    libzHW.o
    [CC]    inflate.o
    [CC]    deflate.o
    [CC]    libcard.o
    [CC]    libddcb.o
    [INFO]  Using ../ext/libcxl/libcxl.a.
    [CC]    ddcb_card.o
    [CC]    wrapper.o
    [CC]    hardware.o
    [CC]    software.o
    [CC]    libzHW.o
    [CC]     libcxl.o
    [CC]     libcxl_sysfs.o
    [CC]    inflate.o
    [CC]    deflate.o
    [CC]    ddcb_card.o
    [LD]    __libzHW.o
    [AR]    libzHW.a
    [CC]    libzHW.so.4.0.16-13-gd441
    [CC]    wrapper.o
    [CC]    libddcb.o
    [CC]     libcxl_sysfs.d
    [SED]    libcxl_sysfs.d
    [CC]    hardware.o
    [CC]     libcxl.d
    [CC]    software.o
    [CC]    libcard.o
    [SED]    libcxl.d
    [CC]     libcxl.so
    [AR]     libcxl.a
    [CC]    ddcb_capi.o
    [CC]    ddcb_capi.o
    [LD]    __libcard.o
    [LD]    __libDDCB.o
    [AR]    libcard.a
    [CC]    libcard.so.4.0.16-13-gd441
    [LD]    __libzADC.o
    [CC]    libDDCB.so.4.0.16-13-gd441
    [AR]    libDDCB.a
    [AR]    libzADC.a
    [CC]    libzADC.so.4.0.16-13-gd441
    [CC]    genwqe_update.o
    [CC]    genwqe_gzip.o
    [CC]    genwqe_gunzip.o
    [CC]    zlib_mt_perf.o
    [CC]    force_cpu.o
    [CC]    genwqe_memcopy.o
    [CC]    genwqe_echo.o
    [CC]    genwqe_peek.o
    [CC]    genwqe_poke.o
    [CC]    genwqe_cksum.o
    [CC]    genwqe_vpd_common.o
    [CC]    genwqe_vpdconv.o
    [CC]    genwqe_vpdupdate.o
    [CC]    genwqe_csv2vpd.o
    [CC]    genwqe_ffdc.o
    [CC]    genwqe_maint.o
    [CC]    genwqe_loadtree.o
    [CC]    genwqe_update
    [CC]    genwqe_peek
    [CC]    genwqe_gzip
    [CC]    genwqe_poke
    [CC]    genwqe_gunzip
    [CC]    genwqe_echo
    [CC]    genwqe_vpdconv
    [CC]    genwqe_cksum
    [CC]    genwqe_vpdupdate
    [CC]    zlib_mt_perf
    [CC]    genwqe_csv2vpd
    [CC]    genwqe_ffdc
    [CC]    genwqe_memcopy
    [CC]    genwqe_loadtree
    [CC]    genwqe_maint
haver@tul2eth3:~/genwqe/genwqe-user$ make -j160
    [INFO]  Using ../ext/libcxl/libcxl.a.
    [CC]    ddcb_capi.o
    [CC]    ddcb_capi.o
    [LD]    __libDDCB.o
    [LD]    __libzADC.o
    [CC]    libDDCB.so.4.0.16-13-gd441
    [AR]    libDDCB.a
    [AR]    libzADC.a
    [CC]    libzADC.so.4.0.16-13-gd441
    [CC]    genwqe_update.o
    [CC]    genwqe_gzip.o
    [CC]    genwqe_gunzip
    [CC]    zlib_mt_perf.o
    [CC]    force_cpu.o
    [CC]    genwqe_memcopy.o
    [CC]    genwqe_echo.o
    [CC]    genwqe_peek.o
    [CC]    genwqe_poke.o
    [CC]    genwqe_cksum.o
    [CC]    genwqe_vpd_common.o
    [CC]    genwqe_vpdconv.o
    [CC]    genwqe_vpdupdate.o
    [CC]    genwqe_csv2vpd.o
    [CC]    genwqe_ffdc.o
    [CC]    genwqe_maint.o
    [CC]    genwqe_loadtree.o
    [CC]    genwqe_gzip
    [CC]    genwqe_peek
    [CC]    genwqe_update
    [CC]    zlib_mt_perf
    [CC]    genwqe_poke
    [CC]    genwqe_echo
    [CC]    genwqe_cksum
    [CC]    genwqe_vpdconv
    [CC]    genwqe_vpdupdate
    [CC]    genwqe_csv2vpd
    [CC]    genwqe_ffdc
    [CC]    genwqe_memcopy
    [CC]    genwqe_loadtree
    [CC]    genwqe_maint
haver@tul2eth3:~/genwqe/genwqe-user$ 

It appears as if anything dependend on libcxl is rebuild. Which is mostly everything for the ppc64le build.

**Comment by fhaverkamp** [comment]
https://github.com/ibm-genwqe/genwqe-user/commit/15029a5edbcf9f0871156c545b251b7f1110b579 should fix this. Eberhard, please retry and let me know if it works now for you. Thanks.
